export const sampleData = [
  {
    id: 1,
    summary: "test naren 1",
    desc: "test naren 1",
    start: "2024-08-02T14:00:00+05:30",
    end: "2024-08-02T16:00:00+05:30",
    attendees:
      "['dilli_project_manager@dataterrain.com', 'mohanrajk@dataterrain.com', 'vinodhini_hr@dataterrain.com']",
    status: null,
    comment: null,
    score: {
      zsdf: 3,
    },
    link: "https://meet.google.com/htq-sdht-vsg",
    user_det: {
      id: 1,
      question_score: null,
      status: null,
      candidate: {
        id: 1,
        candidate_firstName: "mohan",
        candidate_lastName: "raj",
        candidateGender: "male",
        candidateComment: "",
        candidate_email: "mohanrajk@dataterrain.com",
        candidate_dob: null,
        candidate_phoneNumber: null,
        candidateAppliedDate: null,
        candidate_isActive: true,
        candidate_keySkill_Experience: null,
        candidate_yoe: null,
        candidateOtherSkills: null,
        candidateQualification: null,
        candidateWorkMode: null,
        candidate_noticePeriod: null,
        candidate_location: null,
        candidateDistance: null,
        candidateTotalExperience: null,
        candidate_onNotice: null,
        candidate_currentSalary: 0,
        candidate_expectedSalary: 0,
        candidate_resume: null,
        candidate_IsWillingToMove: false,
        candidate_resume_modification: null,
        candidateProfileImage:
          "/media/gallery/images/candidate_avatar_default.svg",
      },
      handled_by: {
        id: 1,
        password:
          "pbkdf2_sha256$600000$HpNkWBqMiuUUFdnTdeuVv9$zBG3PZ93lso71zxtoRokzwVyYa7QvnZrUVBY4BJoqkI=",
        last_login: "2024-08-02T18:01:54.286445+05:30",
        userEmail: "admin_superuser@dataterrain.com",
        username: "admin_superuser",
        firstName: "Admin",
        lastName: "superuser",
        userRole: "admin",
        userPhoneNumber: "",
        userActiveDate: "2024-07-10T22:10:00.348629+05:30",
        userinActiveDate: null,
        userModifiedDate: "2024-07-10T22:31:55.656288+05:30",
        userdateofbirth: null,
        userbloodgroup: null,
        userdescription: null,
        usercity: null,
        userstate: null,
        userzipcode: null,
        usercountry: null,
        userProfileImage: "/media/gallery/images/employee_avatar_default.svg",
        is_staff: true,
        is_active: true,
        is_superuser: true,
        groups: [2, 4],
        user_permissions: [],
      },
      job_id: {
        id: 30,
        jobRequest_Title: "Javascript Developer",
        jobRequest_Role: "Javascript Developer",
        jobRequest_KeySkills:
          "cook analytics french html coding san natural_language_processing e-commerce javascript dom",
        jobRequest_Description: "Job Description goes here",
        jobRequest_Expected_YOE: "0 to 3 years",
        jobRequest_TotalVacancy: 1,
        jobRequest_FilledVacancy: 0,
        jobRequest_isActive: false,
        jobRequest_isClosed: false,
        jobRequest_has_Started: false,
        jobRequest_isPriority: false,
        jobRequest_PriorityValue: 0,
        jobRequest_MoveToAssets: false,
        jobRequest_createdOn: "2024-07-22T15:06:08.603333+05:30",
        jobRequest_Icon: "/media/gallery/images/jd_avatar_default.svg",
        jobRequest_createdBy: 5,
      },
    },
    job_id: {
      id: 11,
      jobRequest_Title: "django developer",
      jobRequest_Role: "software engineer",
      jobRequest_KeySkills: "django",
      jobRequest_Description: "asfffasf",
      jobRequest_Expected_YOE: null,
      jobRequest_TotalVacancy: 1,
      jobRequest_FilledVacancy: 0,
      jobRequest_isActive: true,
      jobRequest_isClosed: false,
      jobRequest_has_Started: true,
      jobRequest_isPriority: false,
      jobRequest_PriorityValue: 0,
      jobRequest_MoveToAssets: false,
      jobRequest_createdOn: "2024-07-11T17:47:33.572939+05:30",
      jobRequest_Icon: "/media/gallery/images/jd_avatar_default.svg",
      jobRequest_createdBy: null,
    },
  },
  {
    id: 2,
    summary: "test naresh",
    desc: "test naresh",
    start: "2024-08-02T14:00:00+05:30",
    end: "2024-08-02T16:00:00+05:30",
    attendees:
      "['dilli_project_manager@dataterrain.com', 'mohanrajk@dataterrain.com', 'vinodhini_hr@dataterrain.com']",
    status: null,
    comment: null,
    score: {
      asdf: 23,
    },
    link: "https://meet.google.com/zxc-vbnm-,./",
    user_det: {
      id: 1,
      question_score: null,
      status: null,
      candidate: {
        id: 1,
        candidate_firstName: "mohan",
        candidate_lastName: "raj",
        candidateGender: "male",
        candidateComment: "",
        candidate_email: "mohanrajk@dataterrain.com",
        candidate_dob: null,
        candidate_phoneNumber: null,
        candidateAppliedDate: null,
        candidate_isActive: true,
        candidate_keySkill_Experience: null,
        candidate_yoe: null,
        candidateOtherSkills: null,
        candidateQualification: null,
        candidateWorkMode: null,
        candidate_noticePeriod: null,
        candidate_location: null,
        candidateDistance: null,
        candidateTotalExperience: null,
        candidate_onNotice: null,
        candidate_currentSalary: 0,
        candidate_expectedSalary: 0,
        candidate_resume: null,
        candidate_IsWillingToMove: false,
        candidate_resume_modification: null,
        candidateProfileImage:
          "/media/gallery/images/candidate_avatar_default.svg",
      },
      handled_by: {
        id: 1,
        password:
          "pbkdf2_sha256$600000$HpNkWBqMiuUUFdnTdeuVv9$zBG3PZ93lso71zxtoRokzwVyYa7QvnZrUVBY4BJoqkI=",
        last_login: "2024-08-02T18:01:54.286445+05:30",
        userEmail: "admin_superuser@dataterrain.com",
        username: "admin_superuser",
        firstName: "Admin",
        lastName: "superuser",
        userRole: "admin",
        userPhoneNumber: "",
        userActiveDate: "2024-07-10T22:10:00.348629+05:30",
        userinActiveDate: null,
        userModifiedDate: "2024-07-10T22:31:55.656288+05:30",
        userdateofbirth: null,
        userbloodgroup: null,
        userdescription: null,
        usercity: null,
        userstate: null,
        userzipcode: null,
        usercountry: null,
        userProfileImage: "/media/gallery/images/employee_avatar_default.svg",
        is_staff: true,
        is_active: true,
        is_superuser: true,
        groups: [2, 4],
        user_permissions: [],
      },
      job_id: {
        id: 30,
        jobRequest_Title: "Javascript Developer",
        jobRequest_Role: "Javascript Developer",
        jobRequest_KeySkills:
          "cook analytics french html coding san natural_language_processing e-commerce javascript dom",
        jobRequest_Description: "Job Description goes here",
        jobRequest_Expected_YOE: "0 to 3 years",
        jobRequest_TotalVacancy: 1,
        jobRequest_FilledVacancy: 0,
        jobRequest_isActive: false,
        jobRequest_isClosed: false,
        jobRequest_has_Started: false,
        jobRequest_isPriority: false,
        jobRequest_PriorityValue: 0,
        jobRequest_MoveToAssets: false,
        jobRequest_createdOn: "2024-07-22T15:06:08.603333+05:30",
        jobRequest_Icon: "/media/gallery/images/jd_avatar_default.svg",
        jobRequest_createdBy: 5,
      },
    },
    job_id: {
      id: 11,
      jobRequest_Title: "django developer",
      jobRequest_Role: "software engineer",
      jobRequest_KeySkills: "django",
      jobRequest_Description: "asfffasf",
      jobRequest_Expected_YOE: null,
      jobRequest_TotalVacancy: 1,
      jobRequest_FilledVacancy: 0,
      jobRequest_isActive: true,
      jobRequest_isClosed: false,
      jobRequest_has_Started: true,
      jobRequest_isPriority: false,
      jobRequest_PriorityValue: 0,
      jobRequest_MoveToAssets: false,
      jobRequest_createdOn: "2024-07-11T17:47:33.572939+05:30",
      jobRequest_Icon: "/media/gallery/images/jd_avatar_default.svg",
      jobRequest_createdBy: null,
    },
  },
  {
    id: 3,
    summary: "test naresh",
    desc: "test naresh",
    start: "2024-08-08T11:08:52+05:30",
    end: "2024-08-08T11:08:52+05:30",
    attendees:
      "['dilli_project_manager@dataterrain.com', 'mohanrajk@dataterrain.com', 'vinodhini_hr@dataterrain.com']",
    status: null,
    comment: null,
    score: {
      SF: 2,
    },
    link: "https://meet.google.com/asd-fghj-kl;",
    user_det: {
      id: 1,
      question_score: null,
      status: null,
      candidate: {
        id: 1,
        candidate_firstName: "mohan",
        candidate_lastName: "raj",
        candidateGender: "male",
        candidateComment: "",
        candidate_email: "mohanrajk@dataterrain.com",
        candidate_dob: null,
        candidate_phoneNumber: null,
        candidateAppliedDate: null,
        candidate_isActive: true,
        candidate_keySkill_Experience: null,
        candidate_yoe: null,
        candidateOtherSkills: null,
        candidateQualification: null,
        candidateWorkMode: null,
        candidate_noticePeriod: null,
        candidate_location: null,
        candidateDistance: null,
        candidateTotalExperience: null,
        candidate_onNotice: null,
        candidate_currentSalary: 0,
        candidate_expectedSalary: 0,
        candidate_resume: null,
        candidate_IsWillingToMove: false,
        candidate_resume_modification: null,
        candidateProfileImage:
          "/media/gallery/images/candidate_avatar_default.svg",
      },
      handled_by: {
        id: 1,
        password:
          "pbkdf2_sha256$600000$HpNkWBqMiuUUFdnTdeuVv9$zBG3PZ93lso71zxtoRokzwVyYa7QvnZrUVBY4BJoqkI=",
        last_login: "2024-08-02T18:01:54.286445+05:30",
        userEmail: "admin_superuser@dataterrain.com",
        username: "admin_superuser",
        firstName: "Admin",
        lastName: "superuser",
        userRole: "admin",
        userPhoneNumber: "",
        userActiveDate: "2024-07-10T22:10:00.348629+05:30",
        userinActiveDate: null,
        userModifiedDate: "2024-07-10T22:31:55.656288+05:30",
        userdateofbirth: null,
        userbloodgroup: null,
        userdescription: null,
        usercity: null,
        userstate: null,
        userzipcode: null,
        usercountry: null,
        userProfileImage: "/media/gallery/images/employee_avatar_default.svg",
        is_staff: true,
        is_active: true,
        is_superuser: true,
        groups: [2, 4],
        user_permissions: [],
      },
      job_id: {
        id: 30,
        jobRequest_Title: "Javascript Developer",
        jobRequest_Role: "Javascript Developer",
        jobRequest_KeySkills:
          "cook analytics french html coding san natural_language_processing e-commerce javascript dom",
        jobRequest_Description: "Job Description goes here",
        jobRequest_Expected_YOE: "0 to 3 years",
        jobRequest_TotalVacancy: 1,
        jobRequest_FilledVacancy: 0,
        jobRequest_isActive: false,
        jobRequest_isClosed: false,
        jobRequest_has_Started: false,
        jobRequest_isPriority: false,
        jobRequest_PriorityValue: 0,
        jobRequest_MoveToAssets: false,
        jobRequest_createdOn: "2024-07-22T15:06:08.603333+05:30",
        jobRequest_Icon: "/media/gallery/images/jd_avatar_default.svg",
        jobRequest_createdBy: 5,
      },
    },
    job_id: {
      id: 13,
      jobRequest_Title: "Developer",
      jobRequest_Role: "Developer",
      jobRequest_KeySkills:
        "development tools api solid configuration methods it maintaining javascript salesforce coding troubleshooting soap deployment",
      jobRequest_Description: "Job Description goes here",
      jobRequest_Expected_YOE: "0 to 3 years",
      jobRequest_TotalVacancy: 16,
      jobRequest_FilledVacancy: 0,
      jobRequest_isActive: false,
      jobRequest_isClosed: false,
      jobRequest_has_Started: false,
      jobRequest_isPriority: false,
      jobRequest_PriorityValue: 0,
      jobRequest_MoveToAssets: false,
      jobRequest_createdOn: "2024-07-12T09:41:47.879827+05:30",
      jobRequest_Icon: "/media/gallery/images/jd_avatar_default.svg",
      jobRequest_createdBy: {
        id: 2,
        password:
          "pbkdf2_sha256$600000$rawrshlQHIZHae13pTGfTt$qKtfw++/01tONB0U8DRFXbUInup0aGM4H6HkqztOBtQ=",
        last_login: null,
        userEmail: "dilli_project_manager@dataterrain.com",
        username: "dilli_rathnam",
        firstName: "Dilli",
        lastName: "Rathnam",
        userRole: "project_manager",
        userPhoneNumber: "",
        userActiveDate: "2024-07-10T22:20:09.049259+05:30",
        userinActiveDate: null,
        userModifiedDate: "2024-07-10T22:31:47.484089+05:30",
        userdateofbirth: null,
        userbloodgroup: null,
        userdescription: null,
        usercity: null,
        userstate: null,
        userzipcode: null,
        usercountry: null,
        userProfileImage: "/media/gallery/images/employee_avatar_default.svg",
        is_staff: false,
        is_active: true,
        is_superuser: false,
        groups: [4, 6],
        user_permissions: [],
      },
    },
  },
  {
    id: 4,
    summary: "test naresh",
    desc: "test naresh",
    start: "2024-08-02T11:14:00+05:30",
    end: "2024-08-02T11:14:02+05:30",
    attendees:
      "['dilli_project_manager@dataterrain.com', 'mohanrajk@dataterrain.com', 'vinodhini_hr@dataterrain.com']",
    status: null,
    comment: null,
    score: {
      asf: 2,
    },
    link: "https://meet.google.com/asd-fghj-kl;",
    user_det: {
      id: 1,
      question_score: null,
      status: null,
      candidate: {
        id: 1,
        candidate_firstName: "mohan",
        candidate_lastName: "raj",
        candidateGender: "male",
        candidateComment: "",
        candidate_email: "mohanrajk@dataterrain.com",
        candidate_dob: null,
        candidate_phoneNumber: null,
        candidateAppliedDate: null,
        candidate_isActive: true,
        candidate_keySkill_Experience: null,
        candidate_yoe: null,
        candidateOtherSkills: null,
        candidateQualification: null,
        candidateWorkMode: null,
        candidate_noticePeriod: null,
        candidate_location: null,
        candidateDistance: null,
        candidateTotalExperience: null,
        candidate_onNotice: null,
        candidate_currentSalary: 0,
        candidate_expectedSalary: 0,
        candidate_resume: null,
        candidate_IsWillingToMove: false,
        candidate_resume_modification: null,
        candidateProfileImage:
          "/media/gallery/images/candidate_avatar_default.svg",
      },
      handled_by: {
        id: 1,
        password:
          "pbkdf2_sha256$600000$HpNkWBqMiuUUFdnTdeuVv9$zBG3PZ93lso71zxtoRokzwVyYa7QvnZrUVBY4BJoqkI=",
        last_login: "2024-08-02T18:01:54.286445+05:30",
        userEmail: "admin_superuser@dataterrain.com",
        username: "admin_superuser",
        firstName: "Admin",
        lastName: "superuser",
        userRole: "admin",
        userPhoneNumber: "",
        userActiveDate: "2024-07-10T22:10:00.348629+05:30",
        userinActiveDate: null,
        userModifiedDate: "2024-07-10T22:31:55.656288+05:30",
        userdateofbirth: null,
        userbloodgroup: null,
        userdescription: null,
        usercity: null,
        userstate: null,
        userzipcode: null,
        usercountry: null,
        userProfileImage: "/media/gallery/images/employee_avatar_default.svg",
        is_staff: true,
        is_active: true,
        is_superuser: true,
        groups: [2, 4],
        user_permissions: [],
      },
      job_id: {
        id: 30,
        jobRequest_Title: "Javascript Developer",
        jobRequest_Role: "Javascript Developer",
        jobRequest_KeySkills:
          "cook analytics french html coding san natural_language_processing e-commerce javascript dom",
        jobRequest_Description: "Job Description goes here",
        jobRequest_Expected_YOE: "0 to 3 years",
        jobRequest_TotalVacancy: 1,
        jobRequest_FilledVacancy: 0,
        jobRequest_isActive: false,
        jobRequest_isClosed: false,
        jobRequest_has_Started: false,
        jobRequest_isPriority: false,
        jobRequest_PriorityValue: 0,
        jobRequest_MoveToAssets: false,
        jobRequest_createdOn: "2024-07-22T15:06:08.603333+05:30",
        jobRequest_Icon: "/media/gallery/images/jd_avatar_default.svg",
        jobRequest_createdBy: 5,
      },
    },
    job_id: {
      id: 11,
      jobRequest_Title: "django developer",
      jobRequest_Role: "software engineer",
      jobRequest_KeySkills: "django",
      jobRequest_Description: "asfffasf",
      jobRequest_Expected_YOE: null,
      jobRequest_TotalVacancy: 1,
      jobRequest_FilledVacancy: 0,
      jobRequest_isActive: true,
      jobRequest_isClosed: false,
      jobRequest_has_Started: true,
      jobRequest_isPriority: false,
      jobRequest_PriorityValue: 0,
      jobRequest_MoveToAssets: false,
      jobRequest_createdOn: "2024-07-11T17:47:33.572939+05:30",
      jobRequest_Icon: "/media/gallery/images/jd_avatar_default.svg",
      jobRequest_createdBy: null,
    },
  },
];
